# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15-stretch-browsers
    environment:
      - BROWSER: headlesschrome
      - CUMULUSCI_KEYCHAIN_CLASS: "cumulusci.core.keychain.EnvironmentProjectKeychain"

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install sfdx
          command: |
            mkdir sfdx
            wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
            ./sfdx/install
            echo 'export PATH=$HOME/repo/sfdx/cli/bin:$PATH' >> $BASH_ENV

      - run:
          name: install Python dependencies
          command: |
            virtualenv venv
            venv/bin/pip install -r requirements_dev.txt

      - run:
          name: run Python tests
          command: |
            mkdir testresults
            venv/bin/tox -e py27 -- --with-coverage --cover-package=cumulusci --with-xunit --xunit-file=testresults/junit.xml

      - run:
          name: create scratch org
          command: |
            echo $SFDX_HUB_KEY | base64 --decode > sfdx.key
            sfdx/cli/bin/sfdx force:auth:jwt:grant --clientid $SFDX_CLIENT_KEY --jwtkeyfile sfdx.key --username $SFDX_HUB_USERNAME --setdefaultdevhubusername -a hub
            venv/bin/cci org info dev
            venv/bin/cci org default dev

      - run:
          name: run CumulusCI robot library tests
          command: |
            venv/bin/coverage run --append venv/bin/cci task run robot -o suites cumulusci/robotframework/tests/cumulusci/base.robot

      - run:
          name: run Salesforce robot library API tests
          command: |
            venv/bin/coverage run --append venv/bin/cci task run robot -o suites cumulusci/robotframework/tests/salesforce/api.robot

      - run:
          name: run Salesforce robot library UI tests
          command: |
            venv/bin/coverage run --append venv/bin/cci task run robot -o suites cumulusci/robotframework/tests/salesforce/ui.robot

      - run:
          name: delete scratch org
          command: |
            venv/bin/cci org scratch_delete dev
          when: always

      - run:
          name: report coverage
          command: |
            venv/bin/coveralls

      - store_artifacts:
          path: testresults

      - save_cache:
          paths:
            - venv
            - .tox
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
